apiVersion: v1
kind: Service
metadata:
  name: alfresco-activemq
  labels:
    app: activemq
spec:
  selector:
    app: activemq
  ports:
    - name: jms
      port: 61616
      targetPort: 61616
    - name: web
      port: 8161
      targetPort: 8161
  type: ClusterIP
  livenessProbe:
          tcpSocket:
            port: 61616
          initialDelaySeconds: 15
          periodSeconds: 10
  eadinessProbe:
          tcpSocket:
            port: 61616
          initialDelaySeconds: 15
          periodSeconds: 10