apiVersion: v1
kind: PersistentVolume
metadata:
  name: alfresco-pv
spec:
  capacity:
    storage: 10Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: /data/alfresco-data
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: alfresco-pvc
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
