apiVersion: v1
kind: Service
metadata:
  name: alfresco-search
  labels:
    app: alfresco-search
spec:
  selector:
    app: alfresco-search
  ports:
    - protocol: TCP
      port: 8983
      targetPort: 8983
