apiVersion: v1
kind: Service
metadata:
  name: alfresco-svc-postgres
  labels:
    app: alfresco-postgres
spec:
  selector:
    app: alfresco-postgres
  type: LoadBalancer
  ports:
    - port: 5432


