apiVersion: v1
kind: Service
metadata:
  name: alfresco-transform-core-aio
  labels:
    app: transform-core-aio
spec:
  selector:
    app: transform-core-aio
  ports:
    - port: 8090
      targetPort: 8090
      protocol: TCP
