apiVersion: v1
kind: Service
metadata:
  name: alfresco-svc-content-app
  labels:
    app: alfresco-content-app
spec:
  selector:
    app: content-app
  type: LoadBalancer
  loadBalancerIP: 172.16.30.211
  ports:
    - port: 8080
      targetPort: 8080
