apiVersion: apps/v1
kind: Deployment
metadata:
  name: alfresco-nginx
  labels:
    app: proxy
spec:
  replicas: 1
  selector:
    matchLabels:
      app: proxy
  template:
    metadata:
      labels:
        app: proxy
    spec:
      containers:
        - name: proxy
          image: nginx:stable-alpine
          resources:
            limits:
              memory: 128m
          livenessProbe:
            tcpSocket:
              port: 80
            initialDelaySeconds: 30
            periodSeconds: 10
          readinessProbe:
            tcpSocket:
              port: 80
            initialDelaySeconds: 30
            periodSeconds: 10
          volumeMounts:
            - name: nginx-config
              mountPath: /etc/nginx/nginx.conf
              subPath: nginx.conf
            - name: nginx-config
              mountPath: /etc/nginx/conf.d/nginx.htpasswd
              subPath: nginx.htpasswd
          volumes:
            - name: nginx-config
              configMap:
                name: nginx-config